### PR TITLE
updated java script

### PR DESCRIPTION
**Pull request by msowers72**
Updated javascript

### CODE REVIEW

**Review by Maalie04 — APPROVED** [review]
updating the js to display dynamically onto the html

**Review by gberhea — APPROVED** [review]
reviewed

**Comment by gberhea** [comment]
Hello , my meeting is extended to 7:45PM
Can we make it tomorrow morning please.

**Comment by Maalie04** [comment]
Ok

**Comment by Maalie04** [comment]
Attached: Untitled document.pdf
Sent using Google Docs https://docs.google.com/

**Pull request merged**
